---
Name: restruct-faqs-config
After: 'framework/*'
---

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Restruct\silverstripe\FAQs\Extensions\SiteTreeExtension

PageController:
  extensions:
    - Restruct\silverstripe\FAQs\Extensions\SiteTreeControllerExtension
